apiVersion : apps/v1
kind: Deployment
metadata:
  name: aztest 
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: aztest 
          command: ["java","-jar","/app.jar"]
          args: ["--spring.config.location=file:/config/application.yml"]
          volumeMounts:
          - mountPath: /mnt/aztest
            name: aztest-volume
            readOnly: false
            subPath: aztest
          - mountPath: /config
            name: application-properties
            readOnly: true
                          
      volumes:
      - name: aztest-volume
        persistentVolumeClaim:
          claimName: ce-aa-pvc
      - name: application-properties
        configMap:
          name: aztest-configmap
          items:
            - key: application.yml
              path: application.yml
          defaultMode: 420
